version: '3.8'

services:
  app:
    build: .
    container_name: pansilius-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    restart: always
